#################################### common config : ####################################

server:
  port: 8080

# 数据库mysql
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: root

#logging
#logging:
#  level:
#    com.lizhizhao.springboot.practice.service: debug


